### ISSUE TITLE
tag the tests which belongs to a host and to a container

### ISSUE THREAD

**Issue by atomic111** [dev-sec/cis-docker-benchmark#8]
add a tag for each test, something like:

tag 'host' for the host security tests 

and

tag 'container' for the container security tests

**Comment by chris-rock** [comment]
Should we add an attribute to define that and assume the host by default?

**Comment by atomic111** [comment]
@chris-rock this sounds also as good idea

**Comment by aaronlippold** [comment]
I would say use the numbers to make that call. If it is about 50/50 then add a tag on each control. If its heavy to one side, make the tag an exception. But I would guess since it is not data that changes, the work to just add a tag to each control would be the best route given that it is a one time event.
